/*****************************************************************************
* Copyright 2013, 2015 Nxtr Automotive, All Rights Reserved.
* Nxtr Confidential
*
* Module File Name  : ePWM.c
* Module Description: eTPWM Complex Device Driver (Not to be regenerated by RTE generator)
* Product           : Gen II Plus - EA3.0
* Author            : Owen Tosh
*****************************************************************************/


/* Version Control:
 * Date Created:      Thu Jan 31 13:14:15 2013
 * %version:          EA3#6 %
 * %derived_by:       jzk9cc %
 *---------------------------------------------------------------------------------------------------------------------
 * Date      Rev      Author    Change Description                                                               SCR #
 * -------   -------  --------  -------------------------------------------------------------------------------  ------
 * 02/04/13  1        Selva     Initial Version
 * 03/11/13  2        OT        Reversed active state for ePWM1-3 (anomaly 4605)
 * 06/17/13  3        OT/Selva        Implemented FDD 34B v003B
 * 04/07/14  4        Selva    Implemented  FDD34B v 005														CR11062
 * 01/25/15  5		  KMC		Updated to ES-34B v008, including A-7586 and A-7798, QAC cleanup                CR12869
 * 24/11/15  6		  Rijvi		Updated per ES-34B v009                                                         EA3#4788
 */

#include "ePwm.h"
#include "ePWM_Cfg.h" 
#include "CalConstants.h"



/* PRQA S 303 EOF 
 * MISRA-C:2004 Rule 11.3: This deviation is required for register access.  The rule is suppressed for the entire file */

/* MISRA-C:2004 Rule 19.1: This deviation is required for AUTOSAR memory map requirements.  Rule suppressed by line at each occurrence. */


#define D_DUTYCYCLESHIFT_CNT_U16    535U  /* Center based PWM duty cycle shift towards the start which avoids mis period update */ 


 
#define EPWM_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */

/******************************************************************************
  * Name:        ePWM_Init1
  * Description: Implements ePWM: Core Configuration subfunction of ES-34B
  * Inputs:      None 
  * Outputs:     None 
  * Usage Notes:  Called from ECU Startup; register access must be performed in privilege mode
  ****************************************************************************/
FUNC(void, EPWM_CODE) ePWM_Init1(void)
{
	
	/* Initialize ePWM1 */
	
	ePWM1->TBCTL = (0U)         /* Counter Mode:                               Up */
				 |  ((uint16)1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | ((uint16)0U << 3U)   /* Use shadow period register:                 Enabled */
				 | ((uint16)0U << 4U)   /* Sync Output Select:                         Sync In */
				 | ((uint16)0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | ((uint16)0U << 10U)  /* Clock Prescale:                             1:1 */
				 | ((uint16)1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM1->TBPRD = 0xFFFFU; /* Set to Max period as period is set by NHET*/
	
	ePWM1->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM1->CMPA = 2499U; /* Init duty cycle of 0% */
	ePWM1->CMPB = 2499U; /* Init duty cycle of 0% */
	
	ePWM1->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | ((uint16)0U << 2U)	/* Counter B Shadow Load Mode:  CTR = zero */ 
				  | ((uint16)0U << 4U)  /* Counter A Shadow Mode:       Enabled */
				  | ((uint16)0U << 6U); /* Counter B Shadow Mode:       Enabled */
	
	ePWM1->AQCTLA = (1U)         /* CTR = zero:                Clear */
				  | ((uint16)0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | ((uint16)2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | ((uint16)0U << 6U)   /* CTR = CMPA,   :Do Nothing */
				  | ((uint16)1U << 8U)   /* CTR = CMPB,   :  Clear */
				  | ((uint16)0U << 10U); /* CTR = CMPB,   :Do Nothing */
	
	ePWM1->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | ((uint16)2U << 2U)   /* Polarity Select:  Invert B */
				 | ((uint16)0U << 4U)   /* In Mode:          Use A for both RED and FED outputs*/
				 | ((uint16)0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM1->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM1->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM1->PCCTL = 0U; /* Disable chopper */
	
	ePWM1->TZCTL = 0x0FFFU; /* Do nothing on all trip-zone conditions */
	
	ePWM1->ETSEL= 0U; /* Disable all events */
	
	
	/* Initialize ePWM2 */
	
	ePWM2->TBCTL = (0U)         /* Counter Mode:                               Up*/
				 | ((uint16)1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | ((uint16)0U << 3U)   /* Use shadow period register:                 Enabled */
				 | ((uint16)0U << 4U)   /* Sync Output Select:                         Sync In */
				 | ((uint16)0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | ((uint16)0U << 10U)  /* Clock Prescale:                             1:1 */
				 | ((uint16)1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM2->TBPRD = 0xFFFFU; /*Set to Max period as period is set by NHET */
	
	ePWM2->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM2->CMPA = 2499U; /* Init duty cycle of 0% */
	ePWM2->CMPB = 2499U; /* Init duty cycle of 0% */
	
	ePWM2->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | ((uint16)0U << 2U)	/* Counter B Shadow Load Mode:  CTR = zero */ 
				  | ((uint16)0U<< 4U)  /* Counter A Shadow Mode:       Enabled */
				  | ((uint16)0U << 6U); /* Counter B Shadow Mode:       Enabled */
	
	ePWM2->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | ((uint16)0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | ((uint16)2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | ((uint16)0U << 6U)   /* CTR = CMPA, 			:  Do nothing*/
				  | ((uint16)1U << 8U)   /* CTR = CMPB, 			:  Clear*/
				  | ((uint16)0U << 10U); /* CTR = CMPB, 			:  Do Nothing */
	
	ePWM2->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | ((uint16)2U << 2U)   /* Polarity Select:  Invert B */
				 | ((uint16)0U << 4U)   /* In Mode:          Use A for both RED and FED outputs */
				 | ((uint16)0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM2->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM2->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM2->PCCTL = 0U; /* Disable chopper */
	
	ePWM2->TZCTL = 0x0FFFU; /* Do nothing on all trip-zone conditions */
	
	ePWM2->ETSEL= 0U; /* Disable all events */
	
	
	/* Initialize ePWM3 */
	
	ePWM3->TBCTL = (0U)         /* Counter Mode:                               Up */
				 | ((uint16)1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | ((uint16)0U << 3U)   /* Use shadow period register:                 Enabled */
				 | ((uint16)0U << 4U)   /* Sync Output Select:                         Sync In */
				 | ((uint16)0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | ((uint16)0U << 10U)  /* Clock Prescale:                             1:1 */
				 | ((uint16)1U << 13U); /* Phase Direction Bit:                        Count Up */
	
	ePWM3->TBPRD = 0xFFFFU; /* Set to Max period as period is set by NHET*/
	
	ePWM3->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM3->CMPA = 2499U; /* Init duty cycle of 0% */
	ePWM3->CMPB = 2499U; /* Init duty cycle of 0% */
	
	ePWM3->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | ((uint16)0U << 2U)	/* Counter B Shadow Load Mode:  CTR = zero */ 
				  | ((uint16)0U << 4U)  /* Counter A Shadow Mode:       Enabled */
				  | ((uint16)0U << 6U); /* Counter B Shadow Mode:       Enabled */
	
	ePWM3->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | ((uint16)0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | ((uint16)2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | ((uint16)0U << 6U)   /* CTR = CMPA,               Do Nothing */
				  | ((uint16)1U << 8U)   /* CTR = CMPB, 			  Clear */
				  | ((uint16)0U << 10U); /* CTR = CMPB, 			  Do Nothing */
	 
	ePWM3->DBCTL = (3U)         /* Out Mode:         Enable both RED and FED */
				 | ((uint16)2U << 2U)   /* Polarity Select:  Invert B */
				 | ((uint16)0U << 4U)   /* In Mode:          Use A for both RED and FED outputs */
				 | ((uint16)0U << 15U); /* Half Cycle:       Use TBCLK rate for DB */
	
	ePWM3->DBRED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM3->DBFED = k_PwmDeadBand_Cnt_u16; /* Initialized with a cal */
	
	ePWM3->PCCTL = 0U; /* Disable chopper */
	
	ePWM3->TZCTL = 0x0FFFU; /* Do nothing on all trip-zone conditions */
	
	ePWM3->ETSEL = 0U; /* Disable all events */
	
	
	/* Initialize ePWM4 */
	
	ePWM4->TBCTL = (0U)         /* Counter Mode:                               Up */
				 | ((uint16)1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | ((uint16)0U << 3U)   /* Use shadow period register:                 Enabled */
				 | ((uint16)0U << 4U)   /* Sync Output Select:                         Sync In */
				 | ((uint16)0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | ((uint16)0U << 10U); /* Clock Prescale:                             1:1 */
	
	ePWM4->TBPRD = 65535U; /* Init with max possible period */
	
	ePWM4->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM4->CMPA = 2499U; /* Init with trigger offset of zero */
	ePWM4->CMPB = 65535U; /* Trigger Disable at init */
	
	ePWM4->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | ((uint16)0U<< 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM4->AQCTLA = (0U)         /* CTR = zero:                Do Nothing */
				  | ((uint16)0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | ((uint16)0U << 4U)   /* CTR = CMPA, incrementing:  Do Nothing */
				  | ((uint16)0U << 6U)   /* CTR = CMPA, decrementing:  Do Nothing */
				  | ((uint16)0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | ((uint16)0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM4->DBCTL = 0U; /* Disable deadband generator */
	
	ePWM4->PCCTL = 0U; /* Disable chopper */
	
	ePWM4->TZCTL = 0x0FFFU; /* Do nothing on all trip-zone conditions */
	
	ePWM4->ETSEL = ((uint16)0U << 3U)   /* Interrupt Enable:  Disabled */
				 | ((uint16)4U << 8U)   /* SOCA Select:       CTR = CMPA, incrementing */
				 | ((uint16)1U << 11U)  /* SOCA Enable:       Enabled */
				 | ((uint16)6U << 12U)  /* SOCB Select:       CTR = CMPB, incrementing */
				 | ((uint16)1U << 15U); /* SOCB Enable:       Enabled */
	
	ePWM4->ETPS = ((uint16)1U << 8U)   /* SOCA Period:  Generate SOCA on every SOCA event */
				| ((uint16)1U << 12U); /* SOCB Period:  Generate SOCB on every SOCB event */
	
	
	/* Initialize ePWM7 */
	
	ePWM7->TBCTL = (0U)         /* Counter Mode:                               Up */
				 | ((uint16)1U << 2U)   /* Counter Register Load from phase register:  Enabled */
				 | ((uint16)0U << 3U)   /* Use shadow period register:                 Enabled */
				 | ((uint16)0U << 4U)   /* Sync Output Select:                         Sync In */
				 | ((uint16)0U << 7U)   /* High Speed Clock Prescale:                  1:1 */
				 | ((uint16)0U << 10U); /* Clock Prescale:                             1:1 */
	
	ePWM7->TBPRD = 65535U; /* Init with max possible period */
	
	ePWM7->TBPHS = 0U; /* Reset to zero on sync */
	
	ePWM7->CMPA = k_PwmRelay_Cnt_u16; /* Initialized with a cal */
	
	ePWM7->CMPCTL = (0U)        /* Counter A Shadow Load Mode:  CTR = zero */
				  | ((uint16)0U << 4U); /* Counter A Shadow Mode:       Enabled */
	
	ePWM7->AQCTLB = (1U)         /* CTR = zero:                Clear */
				  | ((uint16)0U << 2U)   /* CTR = PRD:                 Do Nothing */
				  | ((uint16)2U << 4U)   /* CTR = CMPA, incrementing:  Set */
				  | ((uint16)0U << 6U)   /* CTR = CMPA, decrementing:  Do Nothing */
				  | ((uint16)0U << 8U)   /* CTR = CMPB, incrementing:  Do Nothing */
				  | ((uint16)0U << 10U); /* CTR = CMPB, decrementing:  Do Nothing */
	
	ePWM7->DBCTL = 0U; /* Disable deadband generator */
	
	ePWM7->PCCTL = 0U; /* Disable chopper */
	
	ePWM7->TZCTL = 0x0FFFU; /* Do nothing on all trip-zone conditions */
	
	ePWM7->ETSEL = 0U; /* Disable all events */
	
	
	/* Disable PWM modules 1-3 initially */
	ePWM_DisableOutputs() 
	
}

/******************************************************************************
  * Name:        ePWM_Per1
  * Description: Implements the Motor Control Configuration and ADC SOCA/B subfunctions of ES-34B
  * Inputs:      inputs read by the following macros:
  *					ePWM_Read_PWMPeriod_u16
  *					ePWM_Read_DCPhsAComp_u16
  *					ePWM_Read_DCPhsBComp_u16
  *					ePWM_Read_DCPhsCComp_u16
  *					ePWM_Read_ePWM4CMPB_Cnt_u16
  * Outputs:     outputs written by the ePWM_Write_ePWMxCMPy_Cnt_u16 macros
  * Usage Notes:  Called by the motor control task list
  ****************************************************************************/
FUNC(void, EPWM_CODE) ePWM_Per1(void)
{
	
	VAR(uint16, AUTOMATIC)  halfPWMPeriod_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  PWMPeriod_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	DCPhsAComp_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	DCPhsBComp_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	DCPhsCComp_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	ePWM4CMPB_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	AdjPWMPeriod_Cnt_T_u16;
	
	VAR(uint16, AUTOMATIC) 	CompAPhaseA_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	CompAPhaseB_Cnt_T_u16;
	VAR(uint16, AUTOMATIC) 	CompAPhaseC_Cnt_T_u16;
	
	VAR(uint16, AUTOMATIC)  ePWM1CompA_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  ePWM1CompB_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  ePWM2CompA_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  ePWM2CompB_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  ePWM3CompA_Cnt_T_u16;
	VAR(uint16, AUTOMATIC)  ePWM3CompB_Cnt_T_u16;
	
	
	
	/* Read ePWM duty cycles and periods */
	ePWM_Read_PWMPeriod_u16(&PWMPeriod_Cnt_T_u16);
	ePWM_Read_DCPhsAComp_u16(&DCPhsAComp_Cnt_T_u16);
	ePWM_Read_DCPhsBComp_u16(&DCPhsBComp_Cnt_T_u16);
	ePWM_Read_DCPhsCComp_u16(&DCPhsCComp_Cnt_T_u16);
	ePWM_Read_ePWM4CMPB_Cnt_u16(&ePWM4CMPB_Cnt_T_u16);
	
	
	halfPWMPeriod_Cnt_T_u16 = (uint16)(PWMPeriod_Cnt_T_u16 >> 1U);
	
	/* Adjusted PWM period by subtracting 1 */ 
	AdjPWMPeriod_Cnt_T_u16 = PWMPeriod_Cnt_T_u16 - 1U;
	
	/* Update CompA and CompB Registers of ePWM1 for Phase_A */
	CompAPhaseA_Cnt_T_u16 = (PWMPeriod_Cnt_T_u16 - DCPhsAComp_Cnt_T_u16) >> 1U;
	ePWM1CompA_Cnt_T_u16 = 1U;
	if ( CompAPhaseA_Cnt_T_u16 > D_DUTYCYCLESHIFT_CNT_U16 )
	{
		ePWM1CompA_Cnt_T_u16 = CompAPhaseA_Cnt_T_u16 - D_DUTYCYCLESHIFT_CNT_U16;
	} 
	ePWM1CompB_Cnt_T_u16 = ePWM1CompA_Cnt_T_u16 + DCPhsAComp_Cnt_T_u16;
	if ( ePWM1CompB_Cnt_T_u16 > AdjPWMPeriod_Cnt_T_u16 )
	{
		ePWM1CompB_Cnt_T_u16 = AdjPWMPeriod_Cnt_T_u16;
	}
	
	/* Update CompA and CompB Registers of ePWM2 for Phase_B */
	CompAPhaseB_Cnt_T_u16 = (PWMPeriod_Cnt_T_u16 - DCPhsBComp_Cnt_T_u16) >> 1U;
	ePWM2CompA_Cnt_T_u16 = 1U;
	if ( CompAPhaseB_Cnt_T_u16 > D_DUTYCYCLESHIFT_CNT_U16 )
	{
		ePWM2CompA_Cnt_T_u16 = CompAPhaseB_Cnt_T_u16 - D_DUTYCYCLESHIFT_CNT_U16;
	}
	ePWM2CompB_Cnt_T_u16 = ePWM2CompA_Cnt_T_u16 + DCPhsBComp_Cnt_T_u16;
	if ( ePWM2CompB_Cnt_T_u16 > AdjPWMPeriod_Cnt_T_u16 )
	{
		ePWM2CompB_Cnt_T_u16 = AdjPWMPeriod_Cnt_T_u16;
	}
	
	/* Update CompA and CompB Registers of ePWM3 for Phase_C */
	CompAPhaseC_Cnt_T_u16 = (PWMPeriod_Cnt_T_u16 - DCPhsCComp_Cnt_T_u16) >> 1U;
	ePWM3CompA_Cnt_T_u16 = 1U;
	if ( CompAPhaseC_Cnt_T_u16 > D_DUTYCYCLESHIFT_CNT_U16 )
	{
		ePWM3CompA_Cnt_T_u16 = CompAPhaseC_Cnt_T_u16 - D_DUTYCYCLESHIFT_CNT_U16;
	}
	ePWM3CompB_Cnt_T_u16 = ePWM3CompA_Cnt_T_u16 + DCPhsCComp_Cnt_T_u16;
	if ( ePWM3CompB_Cnt_T_u16 > AdjPWMPeriod_Cnt_T_u16 )
	{
		ePWM3CompB_Cnt_T_u16 = AdjPWMPeriod_Cnt_T_u16;
	}

	/* Write module o/p */
	ePWM_Write_ePWM1CMPA_Cnt_u16(ePWM1CompA_Cnt_T_u16);
	ePWM_Write_ePWM1CMPB_Cnt_u16(ePWM1CompB_Cnt_T_u16);
	ePWM_Write_ePWM2CMPA_Cnt_u16(ePWM2CompA_Cnt_T_u16);
	ePWM_Write_ePWM2CMPB_Cnt_u16(ePWM2CompB_Cnt_T_u16);
	ePWM_Write_ePWM3CMPA_Cnt_u16(ePWM3CompA_Cnt_T_u16);
	ePWM_Write_ePWM3CMPB_Cnt_u16(ePWM3CompB_Cnt_T_u16);
	ePWM_Write_ePWM4CMPA_Cnt_u16((uint16)(uint32)(sint32)(((sint32)halfPWMPeriod_Cnt_T_u16) - k_ADCTrig1Offset_Cnt_s16 - (sint16)D_DUTYCYCLESHIFT_CNT_U16)); 
	ePWM_Write_ePWM4CMPB_Cnt_u16(ePWM4CMPB_Cnt_T_u16);

}

#define EPWM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */

