
#ifndef TCB_H
#define TCB_H

#define TWrapS_XcpWriteAp0 0u
void TRUSTED_TWrapS_XcpWriteAp0(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_CallFblStart 1u
void TRUSTED_TWrapS_CallFblStart(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Adc_Init 2u
void TRUSTED_TWrapS_Adc_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Adc2_Init1 3u
void TRUSTED_TWrapS_Adc2_Init1(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_PwmCdd_Init 4u
void TRUSTED_TWrapS_PwmCdd_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_StaMd_Init0 5u
void TRUSTED_TWrapS_StaMd_Init0(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Wdg_TMS570LS3x_Init 6u
void TRUSTED_TWrapS_Wdg_TMS570LS3x_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_WdgM_Init 7u
void TRUSTED_TWrapS_WdgM_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_NvMProxy_Init 8u
void TRUSTED_TWrapS_NvMProxy_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_FeeIf_Init 9u
void TRUSTED_TWrapS_FeeIf_Init(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_MainFunction 10u
void TRUSTED_TWrapS_Fee_MainFunction(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_Read 11u
void TRUSTED_TWrapS_Fee_Read(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_Write 12u
void TRUSTED_TWrapS_Fee_Write(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_EraseImmediateBlock 13u
void TRUSTED_TWrapS_Fee_EraseImmediateBlock(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_InvalidateBlock 14u
void TRUSTED_TWrapS_Fee_InvalidateBlock(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_Cancel 15u
void TRUSTED_TWrapS_Fee_Cancel(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_GetStatus 16u
void TRUSTED_TWrapS_Fee_GetStatus(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Fee_GetJobResult 17u
void TRUSTED_TWrapS_Fee_GetJobResult(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_uDiagVIM_RednRpdShtdn 18u
void TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_uDiagECC_RednRpdShtdn 19u
void TRUSTED_TWrapS_uDiagECC_RednRpdShtdn(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_Dma_InvalidateSlowADCGroup 20u
void TRUSTED_TWrapS_Dma_InvalidateSlowADCGroup(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define TWrapS_ProcessF0FF 21u
void TRUSTED_TWrapS_ProcessF0FF(TrustedFunctionIndexType Index_Cnt_T_u16, TrustedFunctionParameterRefType Par);
#define NtWrapS_XcpWriteAp6 0u
void NONTRUSTED_NtWrapS_XcpWriteAp6(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_Dem_ClearDTC 1u
void NONTRUSTED_NtWrapS_Dem_ClearDTC(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SrlComDriver_SCom_ElecIntStart 2u
void NONTRUSTED_NtWrapS_SrlComDriver_SCom_ElecIntStart(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SrlComDriver_SCom_ElecIntStop 3u
void NONTRUSTED_NtWrapS_SrlComDriver_SCom_ElecIntStop(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_XcpWriteAp9 4u
void NONTRUSTED_NtWrapS_XcpWriteAp9(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_ActivePull_SCom_SetLTComp 5u
void NONTRUSTED_NtWrapS_ActivePull_SCom_SetLTComp(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_ActivePull_SCom_SetSTComp 6u
void NONTRUSTED_NtWrapS_ActivePull_SCom_SetSTComp(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AvgFricLrn_SCom_ResetToZero 7u
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_ResetToZero(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AvgFricLrn_SCom_InitLearnedTables 8u
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_InitLearnedTables(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AvgFricLrn_SCom_SetSelect 9u
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetSelect(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AvgFricLrn_SCom_SetOffsetOutputDefeat 10u
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetOffsetOutputDefeat(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AvgFricLrn_SCom_SetEOLFric 11u
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetEOLFric(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_BatteryVoltage_SCom_ClearTransOvData 12u
void NONTRUSTED_NtWrapS_BatteryVoltage_SCom_ClearTransOvData(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_IoHwAb_Adc_ResetAdcEnable 13u
void NONTRUSTED_NtWrapS_IoHwAb_Adc_ResetAdcEnable(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_LrnEOT_Scom_ResetEOT 14u
void NONTRUSTED_NtWrapS_LrnEOT_Scom_ResetEOT(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_VehDyn_SCom_ResetCenter 15u
void NONTRUSTED_NtWrapS_VehDyn_SCom_ResetCenter(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_XcpWriteAp10 16u
void NONTRUSTED_NtWrapS_XcpWriteAp10(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AbsHwPos_SCom_CustClrTrim 17u
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_CustClrTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AbsHwPos_SCom_CustSetTrim 18u
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_CustSetTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AbsHwPos_SCom_NxtClearTrim 19u
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_NxtClearTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AbsHwPos_SCom_NxtSetTrim 20u
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_NxtSetTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_AstLmt_Scom_ManualTrqCmd 21u
void NONTRUSTED_NtWrapS_AstLmt_Scom_ManualTrqCmd(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_DigHwTrqSENT_SCom_ClrTrqTrim 22u
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_ClrTrqTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_DigHwTrqSENT_SCom_SetTrqTrim 23u
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_SetTrqTrim(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_DigHwTrqSENT_SCom_WriteData 24u
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_WriteData(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_Polarity_SCom_SetPolarity 25u
void NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SCom_EOLNomMtrParam_Set 26u
void NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SrlComInput_SCom_ManualVehSpd 27u
void NONTRUSTED_NtWrapS_SrlComInput_SCom_ManualVehSpd(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SrlComInput_SCom_ResetTimers 28u
void NONTRUSTED_NtWrapS_SrlComInput_SCom_ResetTimers(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_SrlComInput_SCom_VehSpdControl 29u
void NONTRUSTED_NtWrapS_SrlComInput_SCom_VehSpdControl(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_TrqCanc_Scom_SetCogTrqCal 30u
void NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_TrqCmdScl_SCom_Set 31u
void NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_XcpWriteAp11 32u
void NONTRUSTED_NtWrapS_XcpWriteAp11(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_CmMtrCurr_SCom_CalGain 33u
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalGain(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_CmMtrCurr_SCom_CalOffset 34u
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalOffset(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);
#define NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals 35u
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals(NonTrustedFunctionIndexType Index_Cnt_T_u16, NonTrustedFunctionParameterRefType Par);

#endif
