/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by genTMS570SafeCtxAS.exe, Version: 5.06 */
/* configuration read from: C:\Users\nzx5jd\AppData\Local\Temp\~cfg4_314_EPS.ecuc.arxml.oil */
/* generation at  : Tue Apr 14 15:49:24 2015 */
/* Unlimited license CBD1010124 for Nxtr Automotive */
/* Implementation: TMS570LS3x */
/* Version of general code: 5.23c */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#ifndef _OS_TRUSTFCT_H_
#define _OS_TRUSTFCT_H_

/* Trusted Functions */

#define TWrapS_XcpWriteAp0 0
void TRUSTED_TWrapS_XcpWriteAp0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_CallFblStart 1
void TRUSTED_TWrapS_CallFblStart(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Adc_Init 2
void TRUSTED_TWrapS_Adc_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Adc2_Init1 3
void TRUSTED_TWrapS_Adc2_Init1(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_PwmCdd_Init 4
void TRUSTED_TWrapS_PwmCdd_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_StaMd_Init0 5
void TRUSTED_TWrapS_StaMd_Init0(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Wdg_TMS570LS3x_Init 6
void TRUSTED_TWrapS_Wdg_TMS570LS3x_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_WdgM_Init 7
void TRUSTED_TWrapS_WdgM_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_NvMProxy_Init 8
void TRUSTED_TWrapS_NvMProxy_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_FeeIf_Init 9
void TRUSTED_TWrapS_FeeIf_Init(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_MainFunction 10
void TRUSTED_TWrapS_Fee_MainFunction(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_Read 11
void TRUSTED_TWrapS_Fee_Read(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint16 os_arg_BlockOffset;
   uint8* os_arg_DataBufferPtr;
   uint16 os_arg_Length;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Read;

#define TWrapS_Fee_Write 12
void TRUSTED_TWrapS_Fee_Write(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   uint8* os_arg_DataBufferPtr;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_Write;

#define TWrapS_Fee_EraseImmediateBlock 13
void TRUSTED_TWrapS_Fee_EraseImmediateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_EraseImmediateBlock;

#define TWrapS_Fee_InvalidateBlock 14
void TRUSTED_TWrapS_Fee_InvalidateBlock(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint16 os_arg_BlockNumber;
   Std_ReturnType os_result;
} osTFArgType_TWrapS_Fee_InvalidateBlock;

#define TWrapS_Fee_Cancel 15
void TRUSTED_TWrapS_Fee_Cancel(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Fee_GetStatus 16
void TRUSTED_TWrapS_Fee_GetStatus(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetStatus;

#define TWrapS_Fee_GetJobResult 17
void TRUSTED_TWrapS_Fee_GetJobResult(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_result;
} osTFArgType_TWrapS_Fee_GetJobResult;

#define TWrapS_uDiagVIM_RednRpdShtdn 18
void TRUSTED_TWrapS_uDiagVIM_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_uDiagECC_RednRpdShtdn 19
void TRUSTED_TWrapS_uDiagECC_RednRpdShtdn(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_Dma_InvalidateSlowADCGroup 20
void TRUSTED_TWrapS_Dma_InvalidateSlowADCGroup(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_ProcessF0FF 21
void TRUSTED_TWrapS_ProcessF0FF(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);
#define TWrapS_TI_Fee_SuspendResumeErase 22
void TRUSTED_TWrapS_TI_Fee_SuspendResumeErase(TrustedFunctionIndexType FunctionIndex, TrustedFunctionParameterRefType FunctionParams);

typedef struct
{
   uint8 os_arg_Command;
} osTFArgType_TWrapS_TI_Fee_SuspendResumeErase;



typedef union
{
   osTFArgType_TWrapS_Fee_Read TWrapS_Fee_Read_args;
   osTFArgType_TWrapS_Fee_Write TWrapS_Fee_Write_args;
   osTFArgType_TWrapS_Fee_EraseImmediateBlock TWrapS_Fee_EraseImmediateBlock_args;
   osTFArgType_TWrapS_Fee_InvalidateBlock TWrapS_Fee_InvalidateBlock_args;
   osTFArgType_TWrapS_Fee_GetStatus TWrapS_Fee_GetStatus_args;
   osTFArgType_TWrapS_Fee_GetJobResult TWrapS_Fee_GetJobResult_args;
   osTFArgType_TWrapS_TI_Fee_SuspendResumeErase TWrapS_TI_Fee_SuspendResumeErase_args;
} TrustedFunctionParameterType;

/* Non-trusted Functions */

#define NtWrapS_XcpWriteAp6 0
void NONTRUSTED_NtWrapS_XcpWriteAp6(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Dem_ClearDTC 1
void NONTRUSTED_NtWrapS_Dem_ClearDTC(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SrlComDriver_SCom_ElecIntStart 2
void NONTRUSTED_NtWrapS_SrlComDriver_SCom_ElecIntStart(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SrlComDriver_SCom_ElecIntStop 3
void NONTRUSTED_NtWrapS_SrlComDriver_SCom_ElecIntStop(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp9 4
void NONTRUSTED_NtWrapS_XcpWriteAp9(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_ActivePull_SCom_SetLTComp 5
void NONTRUSTED_NtWrapS_ActivePull_SCom_SetLTComp(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_ActivePull_SCom_SetSTComp 6
void NONTRUSTED_NtWrapS_ActivePull_SCom_SetSTComp(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AvgFricLrn_SCom_ResetToZero 7
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_ResetToZero(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AvgFricLrn_SCom_InitLearnedTables 8
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_InitLearnedTables(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AvgFricLrn_SCom_SetSelect 9
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetSelect(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AvgFricLrn_SCom_SetOffsetOutputDefeat 10
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetOffsetOutputDefeat(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AvgFricLrn_SCom_SetEOLFric 11
void NONTRUSTED_NtWrapS_AvgFricLrn_SCom_SetEOLFric(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_BatteryVoltage_SCom_ClearTransOvData 12
void NONTRUSTED_NtWrapS_BatteryVoltage_SCom_ClearTransOvData(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_IoHwAb_Adc_ResetAdcEnable 13
void NONTRUSTED_NtWrapS_IoHwAb_Adc_ResetAdcEnable(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_LrnEOT_Scom_ResetEOT 14
void NONTRUSTED_NtWrapS_LrnEOT_Scom_ResetEOT(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_VehDyn_SCom_ResetCenter 15
void NONTRUSTED_NtWrapS_VehDyn_SCom_ResetCenter(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp10 16
void NONTRUSTED_NtWrapS_XcpWriteAp10(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SCom_CustClrTrim 17
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_CustClrTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SCom_CustSetTrim 18
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_CustSetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SCom_NxtClearTrim 19
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_NxtClearTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AbsHwPos_SCom_NxtSetTrim 20
void NONTRUSTED_NtWrapS_AbsHwPos_SCom_NxtSetTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_AstLmt_Scom_ManualTrqCmd 21
void NONTRUSTED_NtWrapS_AstLmt_Scom_ManualTrqCmd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigHwTrqSENT_SCom_ClrTrqTrim 22
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_ClrTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigHwTrqSENT_SCom_SetTrqTrim 23
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_SetTrqTrim(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_DigHwTrqSENT_SCom_WriteData 24
void NONTRUSTED_NtWrapS_DigHwTrqSENT_SCom_WriteData(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_Polarity_SCom_SetPolarity 25
void NONTRUSTED_NtWrapS_Polarity_SCom_SetPolarity(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SCom_EOLNomMtrParam_Set 26
void NONTRUSTED_NtWrapS_SCom_EOLNomMtrParam_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SrlComInput_SCom_ManualVehSpd 27
void NONTRUSTED_NtWrapS_SrlComInput_SCom_ManualVehSpd(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SrlComInput_SCom_ResetTimers 28
void NONTRUSTED_NtWrapS_SrlComInput_SCom_ResetTimers(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_SrlComInput_SCom_VehSpdControl 29
void NONTRUSTED_NtWrapS_SrlComInput_SCom_VehSpdControl(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCanc_Scom_SetCogTrqCal 30
void NONTRUSTED_NtWrapS_TrqCanc_Scom_SetCogTrqCal(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_TrqCmdScl_SCom_Set 31
void NONTRUSTED_NtWrapS_TrqCmdScl_SCom_Set(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_XcpWriteAp11 32
void NONTRUSTED_NtWrapS_XcpWriteAp11(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_CalGain 33
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalGain(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_CalOffset 34
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_CalOffset(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);
#define NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals 35
void NONTRUSTED_NtWrapS_CmMtrCurr_SCom_SetMtrCurrCals(NonTrustedFunctionIndexType FunctionIndex, NonTrustedFunctionParameterRefType FunctionParams);



#endif /* _OS_TRUSTFCT_H_  End of File */

/* END OF C:\SynergyProjects\PSA_BMPV_EPS_TMS570-nzx5jd\PSA_BMPV_EPS_TMS570\Tools\AsrProject\..\..\SwProject\Source\GenData\\..\GenDataOS\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
