#ifndef AP_CTRLDDISSHTDN_CFG_H
#define AP_CTRLDDISSHTDN_CFG_H

extern void Rte_Call_CtrldDisShtdn_Per1_CP0_CheckpointReached(void);
extern void Rte_Call_CtrldDisShtdn_Per1_CP1_CheckpointReached(void);
extern void Rte_Call_CtrldDisShtdn_Per1_CP0_CheckpointReached(void);
extern void Rte_Call_CtrldDisShtdn_Per1_CP1_CheckpointReached(void);

#endif