#ifndef SA_DIGHWTRQSENT_CFG_H
#define SA_DIGHWTRQSENT_CFG_H

extern void Rte_Call_DigHwTrqSENT_Per1_CP0_CheckpointReached(void);
extern void Rte_Call_DigHwTrqSENT_Per1_CP1_CheckpointReached(void);
extern void Rte_Call_DigHwTrqSENT_Per2_CP0_CheckpointReached(void);
extern void Rte_Call_DigHwTrqSENT_Per2_CP1_CheckpointReached(void);
extern void Rte_Call_DigHwTrqSENT_Per3_CP0_CheckpointReached(void);
extern void Rte_Call_DigHwTrqSENT_Per3_CP1_CheckpointReached(void);
#endif
