
#ifndef IL_INC_H
#define IL_INC_H

#define kREVEIL_PRINCIPAL_Invalid_3          3
#define kREVEIL_PRINCIPAL_Primary_Request    2
#define kREVEIL_PRINCIPAL_No_Primary_Request 1
#define kREVEIL_PRINCIPAL_Invalid_0          0
#define kETAT_PRINCIP_SEV_DEM                2
#define kETAT_PRINCIP_SEV_Contact            1
#define kETAT_PRINCIP_SEV_Stop               0
#define kETAT_MT_Invalid                     15
#define kETAT_MT_Autonomous_Restart          13
#define kETAT_MT_Autonomous_Starting         10
#define kETAT_MT_Engine_Preparing            7
#define kETAT_MT_Degraded_Restart            6
#define kETAT_MT_Driven_Restart              5
#define kETAT_MT_Stopped                     4
#define kETAT_MT_Engine_Running              3
#define kETAT_MT_Starting                    2
#define kETAT_MT_Cut                         1
#define kETAT_MT_Locked                      0
#define kDIAG_MUX_ON_Enable_SCom_Diagnostics 1
#define kDIAG_MUX_ON_Disable_SCom_Diagnostics 0
#define kVITESSE_VEHICULE_ROUES_Invalid      65535
#define kCODE_DEFAUT_Fault_Code_Exists       1
#define kCODE_DEFAUT_No_Fault_Code           0
#define kETAT_ASSIST_DA_Disability_Parameter 7
#define kETAT_ASSIST_DA_STTd_Assist_Active   4
#define kETAT_ASSIST_DA_STTa_Assist_Active   3
#define kETAT_ASSIST_DA_Dmg_Assist_Active    2
#define kETAT_ASSIST_DA_Nominal_Assist_Active 1
#define kETAT_ASSIST_DA_Assist_Not_Active    0
#define kETAT_LIGNE_APC_Ignition_On          1
#define kETAT_LIGNE_APC_Ignition_Off         0
#define kCPLE_VOLANT_Invalid                 127
#define kETAT_DA_DYN_Invalid                 3
#define kETAT_DA_DYN_Adjustable_Mode         2
#define kETAT_DA_DYN_Dynamic_Mode            1
#define kETAT_DA_DYN_Normal_Mode             0
#define kETAT_DA_2_Reserved                  3
#define kETAT_DA_2_Orange_LED                2
#define kETAT_DA_2_Red_LED                   1
#define kETAT_DA_2_No_Demand                 0
#define kAUTOR_ARRET_MOT_DA_Permission_to_Stop 1
#define kAUTOR_ARRET_MOT_DA_No_Permission_to_Stop 0
#define kDDE_REDEM_DA_Request_Reboot         1
#define kDDE_REDEM_DA_No_Reboot_Required     0
#define kCPLE_VOLANT_OPTMSE_Invalid          127
#define kCAUSE_DESACTIV_CPK_Other_Faults     7
#define kCAUSE_DESACTIV_CPK_EPS_Thermal_Safety_Catch 6
#define kCAUSE_DESACTIV_CPK_Maneuvering_Number_Too_High 5
#define kCAUSE_DESACTIV_CPK_Obstacle_At_Wheel 4
#define kCAUSE_DESACTIV_CPK_Angular_Error_Too_High 3
#define kCAUSE_DESACTIV_CPK_Vehicle_Speed_Too_High 2
#define kCAUSE_DESACTIV_CPK_Driver_Hands_On  1
#define kCAUSE_DESACTIV_CPK_No_Control_Interruption 0
#define kETAT_DAE_CPK_Invalid                3
#define kETAT_DAE_CPK_Control_In_Progress    2
#define kETAT_DAE_CPK_Available              1
#define kETAT_DAE_CPK_Unavailable            0
#define kANGLE_COLONNE_Invalid               32767
#define kVITESSE_COLONNE_Invalid             2047
#define kETAT_SECU_ANGLE_COL_Secure          1
#define kETAT_SECU_ANGLE_COL_Not_Secure      0
#define kDownload_Month_December             12
#define kDownload_Month_November             11
#define kDownload_Month_October              10
#define kDownload_Month_September            9
#define kDownload_Month_August               8
#define kDownload_Month_July                 7
#define kDownload_Month_June                 6
#define kDownload_Month_May                  5
#define kDownload_Month_April                4
#define kDownload_Month_March                3
#define kDownload_Month_February             2
#define kDownload_Month_January              1
#define kMARCHE_AR_BVM_Reverse_Gear_Engaged  1
#define kMARCHE_AR_BVM_Neutral_or_Other_Gear_Engaged 0
#define kCONS_ANGLE_CPK_Invalid              32767
#define kDMD_RELAXE_CPK_Invalid              3
#define kDMD_RELAXE_CPK_Relaxe_Request       2
#define kDMD_RELAXE_CPK_No_Request           1
#define kDMD_RELAXE_CPK_Reserved             0
#define kDMD_FCT_CPK_Invalid                 3
#define kDMD_FCT_CPK_SCP9_Control_Request    2
#define kDMD_FCT_CPK_SCP6_Control_Request    1
#define kDMD_FCT_CPK_No_Request              0
#define kANGLE_VOLANT_Invalid                32767
#define kVITESSE_ROT_VOL_Invalid             255
#define kSENS_ROT_VOL_Clockwise              1
#define kSENS_ROT_VOL_Counter_Clockwise      0
#define kDMD_DELEST_DA_Power_Cut_Request     1
#define kDMD_DELEST_DA_Not_Requested         0
#define kEFFAC_DEFAULT_DIAG_Default_Memory_Erase 1
#define kEFFAC_DEFAULT_DIAG_No_Specific_Action 0
#define kMODE_DIAG_Operation_and_Comm_Inhibited 1
#define kMODE_DIAG_No_Particular_Operation   0
#define kDIAG_INTEGRA_ELEC_No_Frame_Transmission 1
#define kDIAG_INTEGRA_ELEC_No_Particular_Operation 0
#define kVITESSE_VEHICLE_BV_Invalid          65535

#endif
